//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TEST3.rc
//
#define IDCANCEL2                       3
#define IDPREVIEW                       3
#define IDI_ICON1                       101
#define IDR_MENU1                       102
#define IDD_DOM_WORKER                  103
#define IDD_DIP_                        104
#define IDD_NORMAL                      105
#define IDD_DOM_QUEEN                   106
#define IDD_BOOK                        107
#define IDD_BUILDING_BOOK               107
#define IDD_DOM_SOLDIER                 108
#define IDD_BUILDING_UNDER_CONSTRUCTION 109
#define IDD_BUILDING_UNDER_CONSTRUCTION_LAB 111
#define IDD_BUILDING_LAB                111
#define IDD_BUILDING_UNDER_CONSTRUCTION_LIBARAY 112
#define IDD_BUILDING_LIBARAY            112
#define IDD_DIP_SUPPORT                 115
#define IDD_DIP_ATTACK                  116
#define IDC_CURSOR2                     118
#define IDD_BUILDING_EXP                119
#define IDD_DIP_PROPAGATION             120
#define IDD_BATTLE_DEFENCE              121
#define IDD_DIALOG2                     122
#define IDD_BATTLE_ATTACK               122
#define IDD_BUILDING_LAB_INIT           123
#define IDD_BUILDING_HIRED              124
#define IDD_STORY_APHID                 125
#define IDD_EVENT_SELLER                126
#define IDD_DIALOG1                     127
#define IDD_EVENT_FIGHT                 127
#define IDD_ADVISER                     128
#define IDD_NANNY                       129
#define IDD_BATTLE_RESULT               130
#define IDD_GAMEOVER                    132
#define IDD_MAKER                       134
#define IDD_OPTION                      136
#define CURSOR_CROSSHAIR                200
#define IDC_DOM_SLIDER2                 1002
#define IDC_DOM_SLIDER3                 1003
#define IDC_DOM_SLIDER4                 1004
#define IDC_DOM_CHECK1                  1005
#define IDC_DOM_CHECK2                  1006
#define IDC_DOM_CHECK3                  1007
#define IDC_DOM_CHECK4                  1008
#define IDC_RADIO1                      1010
#define IDC_BATTLE_RADIO1               1010
#define IDC_STORY_RADIO1                1010
#define IDC_NANNY_RADIO1                1010
#define IDC_RADIO2                      1011
#define IDC_BATTLE_RADIO2               1011
#define IDC_STORY_RADIO2                1011
#define IDC_NANNY_RADIO2                1011
#define IDC_RADIO3                      1012
#define IDC_NORMAL                      1012
#define IDC_BATTLE_RADIO3               1012
#define IDC_DOM_SLIDER1                 1014
#define IDC_DOM_EDIT1                   1015
#define IDC_STATIC_BUILDING             1020
#define IDC_STATIC_COST                 1021
#define IDC_RADIO4                      1022
#define IDC_STATIC_PERIOD               1022
#define IDC_LIB_RADIO3                  1022
#define IDC_ADVISER_RADIO4              1022
#define IDC_RADIO5                      1023
#define IDC_LIB_RADIO4                  1023
#define IDC_ADVISER_RADIO5              1023
#define IDC_RADIO6                      1024
#define IDC_LIB_RADIO5                  1024
#define IDC_RADIO7                      1025
#define IDC_LIB_RADIO7                  1025
#define IDC_RADIO8                      1026
#define IDC_LIB_RADIO8                  1026
#define IDC_RADIO9                      1027
#define IDC_LIB_RADIO9                  1027
#define IDC_RADIO10                     1028
#define IDC_LIB_RADIO10                 1028
#define IDC_RADIO12                     1029
#define IDC_LIB_RADIO11                 1029
#define IDC_RADIO11                     1030
#define IDC_LIB_RADIO6                  1030
#define IDC_BUTTON1                     1031
#define IDC_LAB_BUTTON1                 1031
#define IDC_RADIO13                     1032
#define IDC_WORKER_MUSHROOM             1032
#define IDC_LIB_RADIO12                 1032
#define IDC_RADIO14                     1033
#define IDC_BUTTON2                     1033
#define IDC_WORKER_APHID                1033
#define IDC_LIB_RADIO13                 1033
#define IDC_LAB_BUTTON2                 1033
#define IDC_BUTTON3                     1034
#define IDC_STATIC_DOM                  1034
#define IDC_LAB_BUTTON3                 1034
#define IDC_BUTTON4                     1035
#define IDC_SLIDER1                     1035
#define IDC_LAB_BUTTON4                 1035
#define IDC_BUTTON5                     1036
#define IDC_SLIDER2                     1036
#define IDC_DIP_SLIDER2                 1036
#define IDC_LAB_BUTTON5                 1036
#define IDC_SLIDER3                     1037
#define IDC_DIP_SLIDER3                 1037
#define IDC_LIB_BUTTON2                 1037
#define IDC_SLIDER4                     1038
#define IDC_LIB_BUTTON3                 1038
#define IDC_BUTTON6                     1039
#define IDC_DIP_SLIDER1                 1039
#define IDC_LIB_BUTTON4                 1039
#define IDC_LAB_BUTTON6                 1039
#define IDC_BUTTON7                     1040
#define IDC_DOM_EDIT2                   1040
#define IDC_LIB_BUTTON5                 1040
#define IDC_LAB_BUTTON7                 1040
#define IDC_BUTTON8                     1041
#define IDC_DOM_EDIT3                   1041
#define IDC_LIB_BUTTON6                 1041
#define IDC_LAB_BUTTON8                 1041
#define IDC_BUTTON9                     1042
#define IDC_DIP_EDIT1                   1042
#define IDC_LIB_BUTTON7                 1042
#define IDC_LAB_BUTTON9                 1042
#define IDC_DIP_EDIT2                   1043
#define IDC_LIB_BUTTON8                 1043
#define IDC_LIB_RADIO1                  1044
#define IDC_LIB_RADIO2                  1045
#define IDC_LIB_BUTTON9                 1046
#define IDC_LIB_BUTTON10                1047
#define IDC_LIB_BUTTON11                1048
#define IDC_LIB_BUTTON12                1049
#define IDC_LIB_BUTTON13                1050
#define IDC_LIB_BUTTON1                 1051
#define IDC_STATIC_EXP                  1052
#define IDC_STATIC_BOOK                 1053
#define IDNEXT                          1054
#define IDC_DIP_EDIT3                   1055
#define IDC_STATIC_BATTLE               1055
#define IDC_DIP_EDIT4                   1056
#define IDC_HIRED_CHECK1                1056
#define IDC_STATIC_HIRED                1057
#define IDC_STATIC_PLACE                1061
#define IDC_STATIC_PLAYER_DEM           1062
#define IDC_STATIC_SPE_DEM              1063
#define IDC_STATIC_RESOURCE             1064
#define IDC_EVE_RADIO1                  1065
#define IDC_EVE_RADIO2                  1066
#define IDC_EVE_RADIO3                  1067
#define IDC_STATIC_FIGHT                1068
#define IDC_STATIC_ITEM                 1069
#define IDC_STATIC_STR_ATT              1070
#define IDC_STATIC_ITEM_COST            1070
#define IDC_STATIC_STR_DEF              1071
#define IDC_ADVISER_RADIO1              1073
#define IDC_ADVISER_RADIO2              1074
#define IDC_STATIC_GAMEOVER             1075
#define IDC_ADVISER_RADIO3              1076
#define IDC_OPT_EDIT1                   1076
#define IDC_OPT_STATIC                  1078
#define IDC_STATIC_OPT                  1078

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
